apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connect
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
      - name: connect
        image: connect:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003